version: '3'
services:
  server1:
    build: ./server1
    ports:
      - "3000:3000"
    networks:
      - app-network

  server2:
    build: ./server2
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge